from python:3.11-slim
# install ffmpeg
RUN apt-get update && apt-get install -y ffmpeg openssh-server

WORKDIR /app

COPY ./api /app/api
COPY ./migrations /app/migrations
COPY alembic.ini backend_startup.sh poetry.lock pyproject.toml README.md /app/

RUN pip install poetry && \
	poetry config virtualenvs.create false && \
	poetry install --no-dev --no-interaction --no-ansi

RUN chmod 0700 ~/.ssh

EXPOSE 8000

CMD ["/bin/bash", "backend_startup.sh"]