# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictBytes, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Set
from typing_extensions import Self


class CustomDocumentParsingAsyncRequest(BaseModel):
    """
    CustomDocumentParsingAsyncRequest
    """  # noqa: E501

    providers: Annotated[str, Field(min_length=1, strict=True)] = Field(
        description="It can be one (ex: **'amazon'** or **'google'**) or multiple provider(s) (ex: **'amazon,microsoft,google'**)             that the data will be redirected to in order to get the processed results."
    )
    fallback_providers: Optional[StrictStr] = Field(
        default=None,
        description="Providers in this list will be used as fallback if the call to provider in `providers` parameter fails.     To use this feature, you must input **only one** provider in the `providers` parameter. but you can put up to 5 fallbacks.  They will be tried in the same order they are input, and it will stop to the first provider who doesn't fail.   *Doesn't work with async subfeatures.*     ",
    )
    show_original_response: Optional[StrictBool] = Field(
        default=False,
        description="Optional : Shows the original response of the provider.<br>         When set to **true**, a new attribute *original_response* will appear in the response object.",
    )
    webhook_receiver: Optional[Annotated[str, Field(min_length=1, strict=True)]] = (
        Field(
            default=None,
            description="Webhook receiver should be a valid https URL (ex : https://your.listner.com/endpoint).             After the processing is done, the webhook endpoint will receive a POST request with the result.",
        )
    )
    users_webhook_parameters: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Json data that contains of additional parameters that will be sent back to the webhook receiver             (ex: api key for security or client's data ID to link the result internally).             Will only be used when webhook_receiver is set.",
    )
    file: Optional[Union[StrictBytes, StrictStr]] = Field(
        default=None,
        description="File to analyse in binary format to be used with *content-type*: **multipart/form-data** <br> **Does not work with application/json !**",
    )
    file_url: Optional[StrictStr] = Field(
        default=None,
        description="File **URL** to analyse to be used with with *content-type*: **application/json**.",
    )
    file_password: Optional[Annotated[str, Field(strict=True, max_length=200)]] = Field(
        default=None,
        description="If your PDF file has a password, you can pass it here!",
    )
    queries: Annotated[str, Field(min_length=1, strict=True)] = Field(
        description="Your queries need to be a list of dict containing the questions you want answered and the page to look for the information in :  '[{'query':'your query','pages':'your pages'},{'query':'your query','pages':'your pages'}]'"
    )
    convert_to_pdf: Optional[StrictBool] = Field(
        default=False,
        description="Boolean value to specify weather to convert the doc/docx files to pdf format to be accepted by a majority of the providers",
    )
    __properties: ClassVar[List[str]] = [
        "providers",
        "fallback_providers",
        "show_original_response",
        "webhook_receiver",
        "users_webhook_parameters",
        "file",
        "file_url",
        "file_password",
        "queries",
        "convert_to_pdf",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomDocumentParsingAsyncRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if fallback_providers (nullable) is None
        # and model_fields_set contains the field
        if (
            self.fallback_providers is None
            and "fallback_providers" in self.model_fields_set
        ):
            _dict["fallback_providers"] = None

        # set to None if file_url (nullable) is None
        # and model_fields_set contains the field
        if self.file_url is None and "file_url" in self.model_fields_set:
            _dict["file_url"] = None

        # set to None if file_password (nullable) is None
        # and model_fields_set contains the field
        if self.file_password is None and "file_password" in self.model_fields_set:
            _dict["file_password"] = None

        # set to None if convert_to_pdf (nullable) is None
        # and model_fields_set contains the field
        if self.convert_to_pdf is None and "convert_to_pdf" in self.model_fields_set:
            _dict["convert_to_pdf"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomDocumentParsingAsyncRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "providers": obj.get("providers"),
                "fallback_providers": obj.get("fallback_providers"),
                "show_original_response": obj.get("show_original_response")
                if obj.get("show_original_response") is not None
                else False,
                "webhook_receiver": obj.get("webhook_receiver"),
                "users_webhook_parameters": obj.get("users_webhook_parameters"),
                "file": obj.get("file"),
                "file_url": obj.get("file_url"),
                "file_password": obj.get("file_password"),
                "queries": obj.get("queries"),
                "convert_to_pdf": obj.get("convert_to_pdf")
                if obj.get("convert_to_pdf") is not None
                else False,
            }
        )
        return _obj
