# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.pydantic_main_ocranonymization_async_anonymization_async_data_class94559363905696 import (
    PydanticMainOcranonymizationAsyncAnonymizationAsyncDataClass94559363905696,
)
from openapi_client.models.pydantic_main_ocranonymization_async_anonymization_async_data_class94559367866672 import (
    PydanticMainOcranonymizationAsyncAnonymizationAsyncDataClass94559367866672,
)
from openapi_client.models.pydantic_main_ocranonymization_async_anonymization_async_data_class94559367974464 import (
    PydanticMainOcranonymizationAsyncAnonymizationAsyncDataClass94559367974464,
)
from typing import Set
from typing_extensions import Self


class OcranonymizationAsyncModel(BaseModel):
    """
    OcranonymizationAsyncModel
    """  # noqa: E501

    var_base64: Optional[
        PydanticMainOcranonymizationAsyncAnonymizationAsyncDataClass94559363905696
    ] = Field(default=None, alias="base64")
    privateai: Optional[
        PydanticMainOcranonymizationAsyncAnonymizationAsyncDataClass94559367866672
    ] = None
    readyredact: Optional[
        PydanticMainOcranonymizationAsyncAnonymizationAsyncDataClass94559367974464
    ] = None
    __properties: ClassVar[List[str]] = ["base64", "privateai", "readyredact"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OcranonymizationAsyncModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_base64
        if self.var_base64:
            _dict["base64"] = self.var_base64.to_dict()
        # override the default output from pydantic by calling `to_dict()` of privateai
        if self.privateai:
            _dict["privateai"] = self.privateai.to_dict()
        # override the default output from pydantic by calling `to_dict()` of readyredact
        if self.readyredact:
            _dict["readyredact"] = self.readyredact.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OcranonymizationAsyncModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "base64": PydanticMainOcranonymizationAsyncAnonymizationAsyncDataClass94559363905696.from_dict(
                    obj["base64"]
                )
                if obj.get("base64") is not None
                else None,
                "privateai": PydanticMainOcranonymizationAsyncAnonymizationAsyncDataClass94559367866672.from_dict(
                    obj["privateai"]
                )
                if obj.get("privateai") is not None
                else None,
                "readyredact": PydanticMainOcranonymizationAsyncAnonymizationAsyncDataClass94559367974464.from_dict(
                    obj["readyredact"]
                )
                if obj.get("readyredact") is not None
                else None,
            }
        )
        return _obj
