# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.api.plagia_detection_api import PlagiaDetectionApi


class TestPlagiaDetectionApi(unittest.TestCase):
    """PlagiaDetectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlagiaDetectionApi()

    def tearDown(self) -> None:
        pass

    def test_text_text_plagia_detection_create(self) -> None:
        """Test case for text_text_plagia_detection_create

        Plagia Detection
        """
        pass


if __name__ == "__main__":
    unittest.main()
