# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.resume_personal_info import ResumePersonalInfo


class TestResumePersonalInfo(unittest.TestCase):
    """ResumePersonalInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResumePersonalInfo:
        """Test ResumePersonalInfo
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ResumePersonalInfo`
        """
        model = ResumePersonalInfo()
        if include_optional:
            return ResumePersonalInfo(
                name = openapi_client.models.resume_personal_name.ResumePersonalName(
                    first_name = '', 
                    last_name = '', 
                    raw_name = '', 
                    middle = '', 
                    title = '', 
                    prefix = '', 
                    sufix = '', ),
                address = openapi_client.models.resume_location.ResumeLocation(
                    formatted_location = '', 
                    postal_code = '', 
                    region = '', 
                    country = '', 
                    country_code = '', 
                    raw_input_location = '', 
                    street = '', 
                    street_number = '', 
                    appartment_number = '', 
                    city = '', ),
                self_summary = '',
                objective = '',
                date_of_birth = '',
                place_of_birth = '',
                phones = [
                    ''
                    ],
                mails = [
                    ''
                    ],
                urls = [
                    ''
                    ],
                fax = [
                    ''
                    ],
                current_profession = '',
                gender = '',
                nationality = '',
                martial_status = '',
                current_salary = ''
            )
        else:
            return ResumePersonalInfo(
                name = openapi_client.models.resume_personal_name.ResumePersonalName(
                    first_name = '', 
                    last_name = '', 
                    raw_name = '', 
                    middle = '', 
                    title = '', 
                    prefix = '', 
                    sufix = '', ),
                address = openapi_client.models.resume_location.ResumeLocation(
                    formatted_location = '', 
                    postal_code = '', 
                    region = '', 
                    country = '', 
                    country_code = '', 
                    raw_input_location = '', 
                    street = '', 
                    street_number = '', 
                    appartment_number = '', 
                    city = '', ),
                self_summary = '',
                objective = '',
                date_of_birth = '',
                place_of_birth = '',
                current_profession = '',
                gender = '',
                nationality = '',
                martial_status = '',
                current_salary = '',
        )
        """

    def testResumePersonalInfo(self):
        """Test ResumePersonalInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
