# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.landmark_location import LandmarkLocation


class TestLandmarkLocation(unittest.TestCase):
    """LandmarkLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LandmarkLocation:
        """Test LandmarkLocation
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `LandmarkLocation`
        """
        model = LandmarkLocation()
        if include_optional:
            return LandmarkLocation(
                lat_lng = openapi_client.models.landmark_lat_lng.LandmarkLatLng(
                    latitude = 56, 
                    longitude = 56, )
            )
        else:
            return LandmarkLocation(
                lat_lng = openapi_client.models.landmark_lat_lng.LandmarkLatLng(
                    latitude = 56, 
                    longitude = 56, ),
        )
        """

    def testLandmarkLocation(self):
        """Test LandmarkLocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
