# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.pydantic_main_textemotion_detection_emotion_detection_data_class94559370080560 import (
    PydanticMainTextemotionDetectionEmotionDetectionDataClass94559370080560,
)


class TestPydanticMainTextemotionDetectionEmotionDetectionDataClass94559370080560(
    unittest.TestCase
):
    """PydanticMainTextemotionDetectionEmotionDetectionDataClass94559370080560 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> PydanticMainTextemotionDetectionEmotionDetectionDataClass94559370080560:
        """Test PydanticMainTextemotionDetectionEmotionDetectionDataClass94559370080560
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PydanticMainTextemotionDetectionEmotionDetectionDataClass94559370080560`
        """
        model = PydanticMainTextemotionDetectionEmotionDetectionDataClass94559370080560()
        if include_optional:
            return PydanticMainTextemotionDetectionEmotionDetectionDataClass94559370080560(
                text = '',
                items = [
                    openapi_client.models.emotion_item.EmotionItem(
                        emotion = '', 
                        emotion_score = 0, )
                    ],
                original_response = None,
                status = 'success'
            )
        else:
            return PydanticMainTextemotionDetectionEmotionDetectionDataClass94559370080560(
                text = '',
                status = 'success',
        )
        """

    def testPydanticMainTextemotionDetectionEmotionDetectionDataClass94559370080560(
        self,
    ):
        """Test PydanticMainTextemotionDetectionEmotionDetectionDataClass94559370080560"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
