# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.pydantic_main_textcustom_named_entity_recognition_custom_named_entity_recognition_data_class94559369070736 import (
    PydanticMainTextcustomNamedEntityRecognitionCustomNamedEntityRecognitionDataClass94559369070736,
)


class TestPydanticMainTextcustomNamedEntityRecognitionCustomNamedEntityRecognitionDataClass94559369070736(
    unittest.TestCase
):
    """PydanticMainTextcustomNamedEntityRecognitionCustomNamedEntityRecognitionDataClass94559369070736 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> PydanticMainTextcustomNamedEntityRecognitionCustomNamedEntityRecognitionDataClass94559369070736:
        """Test PydanticMainTextcustomNamedEntityRecognitionCustomNamedEntityRecognitionDataClass94559369070736
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PydanticMainTextcustomNamedEntityRecognitionCustomNamedEntityRecognitionDataClass94559369070736`
        """
        model = PydanticMainTextcustomNamedEntityRecognitionCustomNamedEntityRecognitionDataClass94559369070736()
        if include_optional:
            return PydanticMainTextcustomNamedEntityRecognitionCustomNamedEntityRecognitionDataClass94559369070736(
                items = [
                    openapi_client.models.infos_custom_named_entity_recognition_data_class.InfosCustomNamedEntityRecognitionDataClass(
                        entity = '', 
                        category = '', )
                    ],
                original_response = None,
                status = 'success'
            )
        else:
            return PydanticMainTextcustomNamedEntityRecognitionCustomNamedEntityRecognitionDataClass94559369070736(
                status = 'success',
        )
        """

    def testPydanticMainTextcustomNamedEntityRecognitionCustomNamedEntityRecognitionDataClass94559369070736(
        self,
    ):
        """Test PydanticMainTextcustomNamedEntityRecognitionCustomNamedEntityRecognitionDataClass94559369070736"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
