# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.content_nsfw import ContentNSFW


class TestContentNSFW(unittest.TestCase):
    """ContentNSFW unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentNSFW:
        """Test ContentNSFW
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ContentNSFW`
        """
        model = ContentNSFW()
        if include_optional:
            return ContentNSFW(
                timestamp = 56,
                confidence = 56,
                category = ''
            )
        else:
            return ContentNSFW(
                timestamp = 56,
                confidence = 56,
                category = '',
        )
        """

    def testContentNSFW(self):
        """Test ContentNSFW"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
