# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.infos_syntax_analysis_data_class import (
    InfosSyntaxAnalysisDataClass,
)


class TestInfosSyntaxAnalysisDataClass(unittest.TestCase):
    """InfosSyntaxAnalysisDataClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InfosSyntaxAnalysisDataClass:
        """Test InfosSyntaxAnalysisDataClass
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `InfosSyntaxAnalysisDataClass`
        """
        model = InfosSyntaxAnalysisDataClass()
        if include_optional:
            return InfosSyntaxAnalysisDataClass(
                word = '',
                importance = 56,
                tag = '',
                lemma = '',
                others = openapi_client.models.others.Others()
            )
        else:
            return InfosSyntaxAnalysisDataClass(
                word = '',
                importance = 56,
                tag = '',
                lemma = '',
        )
        """

    def testInfosSyntaxAnalysisDataClass(self):
        """Test InfosSyntaxAnalysisDataClass"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
