# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.imagequestion_answer_question_answer_request import (
    ImagequestionAnswerQuestionAnswerRequest,
)


class TestImagequestionAnswerQuestionAnswerRequest(unittest.TestCase):
    """ImagequestionAnswerQuestionAnswerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> ImagequestionAnswerQuestionAnswerRequest:
        """Test ImagequestionAnswerQuestionAnswerRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ImagequestionAnswerQuestionAnswerRequest`
        """
        model = ImagequestionAnswerQuestionAnswerRequest()
        if include_optional:
            return ImagequestionAnswerQuestionAnswerRequest(
                providers = '0',
                fallback_providers = '',
                response_as_dict = True,
                attributes_as_list = True,
                show_original_response = True,
                settings = '',
                file = bytes(b'blah'),
                file_url = '',
                temperature = 0,
                question = '0',
                max_tokens = 1
            )
        else:
            return ImagequestionAnswerQuestionAnswerRequest(
                providers = '0',
        )
        """

    def testImagequestionAnswerQuestionAnswerRequest(self):
        """Test ImagequestionAnswerQuestionAnswerRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
