# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.imagequestion_answer_response_model import (
    ImagequestionAnswerResponseModel,
)


class TestImagequestionAnswerResponseModel(unittest.TestCase):
    """ImagequestionAnswerResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImagequestionAnswerResponseModel:
        """Test ImagequestionAnswerResponseModel
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ImagequestionAnswerResponseModel`
        """
        model = ImagequestionAnswerResponseModel()
        if include_optional:
            return ImagequestionAnswerResponseModel(
                openai = openapi_client.models.imagequestion_answer_question_answer_data_class.imagequestion_answerQuestionAnswerDataClass(
                    answers = [
                        ''
                        ], 
                    original_response = null, 
                    status = null, ),
                alephalpha = openapi_client.models.imagequestion_answer_question_answer_data_class.imagequestion_answerQuestionAnswerDataClass(
                    answers = [
                        ''
                        ], 
                    original_response = null, 
                    status = null, ),
                google = openapi_client.models.imagequestion_answer_question_answer_data_class.imagequestion_answerQuestionAnswerDataClass(
                    answers = [
                        ''
                        ], 
                    original_response = null, 
                    status = null, )
            )
        else:
            return ImagequestionAnswerResponseModel(
        )
        """

    def testImagequestionAnswerResponseModel(self):
        """Test ImagequestionAnswerResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
