# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.asset_update_request import AssetUpdateRequest


class TestAssetUpdateRequest(unittest.TestCase):
    """AssetUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetUpdateRequest:
        """Test AssetUpdateRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AssetUpdateRequest`
        """
        model = AssetUpdateRequest()
        if include_optional:
            return AssetUpdateRequest(
                sub_resource = '0',
                data = {
                    'key' : null
                    }
            )
        else:
            return AssetUpdateRequest(
                sub_resource = '0',
                data = {
                    'key' : null
                    },
        )
        """

    def testAssetUpdateRequest(self):
        """Test AssetUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
