# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest


class TestMiscellaneousSubCategoryType(unittest.TestCase):
    """MiscellaneousSubCategoryType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMiscellaneousSubCategoryType(self):
        """Test MiscellaneousSubCategoryType"""
        # inst = MiscellaneousSubCategoryType()


if __name__ == "__main__":
    unittest.main()
