# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest


class TestRepresentationEnum(unittest.TestCase):
    """RepresentationEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepresentationEnum(self):
        """Test RepresentationEnum"""
        # inst = RepresentationEnum()


if __name__ == "__main__":
    unittest.main()
