# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.financial_line_item import FinancialLineItem


class TestFinancialLineItem(unittest.TestCase):
    """FinancialLineItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FinancialLineItem:
        """Test FinancialLineItem
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FinancialLineItem`
        """
        model = FinancialLineItem()
        if include_optional:
            return FinancialLineItem(
                tax = 56,
                amount_line = 56,
                description = '',
                quantity = 56,
                unit_price = 56,
                unit_type = '',
                var_date = '',
                product_code = '',
                purchase_order = '',
                tax_rate = 56,
                base_total = 56,
                sub_total = 56,
                discount_amount = 56,
                discount_rate = 56,
                discount_code = '',
                order_number = '',
                title = ''
            )
        else:
            return FinancialLineItem(
        )
        """

    def testFinancialLineItem(self):
        """Test FinancialLineItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
