# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.api.speech_to_text_async_api import SpeechToTextAsyncApi


class TestSpeechToTextAsyncApi(unittest.TestCase):
    """SpeechToTextAsyncApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SpeechToTextAsyncApi()

    def tearDown(self) -> None:
        pass

    def test_audio_audio_speech_to_text_async_create(self) -> None:
        """Test case for audio_audio_speech_to_text_async_create

        Speech to Text Launch Job
        """
        pass

    def test_audio_audio_speech_to_text_async_destroy(self) -> None:
        """Test case for audio_audio_speech_to_text_async_destroy

        Speech to text delete Jobs
        """
        pass

    def test_audio_audio_speech_to_text_async_retrieve(self) -> None:
        """Test case for audio_audio_speech_to_text_async_retrieve

        Speech to Text List Jobs
        """
        pass

    def test_audio_audio_speech_to_text_async_retrieve2(self) -> None:
        """Test case for audio_audio_speech_to_text_async_retrieve2

        Speech to Text Get Job Results
        """
        pass


if __name__ == "__main__":
    unittest.main()
