# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest


class TestFinancialInformationSubCategoryType(unittest.TestCase):
    """FinancialInformationSubCategoryType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFinancialInformationSubCategoryType(self):
        """Test FinancialInformationSubCategoryType"""
        # inst = FinancialInformationSubCategoryType()


if __name__ == "__main__":
    unittest.main()
