# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.boundix_box_ocr_table import BoundixBoxOCRTable


class TestBoundixBoxOCRTable(unittest.TestCase):
    """BoundixBoxOCRTable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BoundixBoxOCRTable:
        """Test BoundixBoxOCRTable
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BoundixBoxOCRTable`
        """
        model = BoundixBoxOCRTable()
        if include_optional:
            return BoundixBoxOCRTable(
                left = 56,
                top = 56,
                width = 56,
                height = 56
            )
        else:
            return BoundixBoxOCRTable(
                left = 56,
                top = 56,
                width = 56,
                height = 56,
        )
        """

    def testBoundixBoxOCRTable(self):
        """Test BoundixBoxOCRTable"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
