# coding: utf-8

"""
Eden AI

Your project description

The version of the OpenAPI document: 2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.textcustom_named_entity_recognition_response_model import (
    TextcustomNamedEntityRecognitionResponseModel,
)


class TestTextcustomNamedEntityRecognitionResponseModel(unittest.TestCase):
    """TextcustomNamedEntityRecognitionResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> TextcustomNamedEntityRecognitionResponseModel:
        """Test TextcustomNamedEntityRecognitionResponseModel
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TextcustomNamedEntityRecognitionResponseModel`
        """
        model = TextcustomNamedEntityRecognitionResponseModel()
        if include_optional:
            return TextcustomNamedEntityRecognitionResponseModel(
                cohere = openapi_client.models.textcustom_named_entity_recognition_custom_named_entity_recognition_data_class.textcustom_named_entity_recognitionCustomNamedEntityRecognitionDataClass(
                    items = [
                        openapi_client.models.infos_custom_named_entity_recognition_data_class.InfosCustomNamedEntityRecognitionDataClass(
                            entity = '', 
                            category = '', )
                        ], 
                    original_response = null, 
                    status = null, ),
                openai = openapi_client.models.textcustom_named_entity_recognition_custom_named_entity_recognition_data_class.textcustom_named_entity_recognitionCustomNamedEntityRecognitionDataClass(
                    items = [
                        openapi_client.models.infos_custom_named_entity_recognition_data_class.InfosCustomNamedEntityRecognitionDataClass(
                            entity = '', 
                            category = '', )
                        ], 
                    original_response = null, 
                    status = null, ),
                eden_ai = openapi_client.models.textcustom_named_entity_recognition_custom_named_entity_recognition_data_class.textcustom_named_entity_recognitionCustomNamedEntityRecognitionDataClass(
                    items = [
                        openapi_client.models.infos_custom_named_entity_recognition_data_class.InfosCustomNamedEntityRecognitionDataClass(
                            entity = '', 
                            category = '', )
                        ], 
                    original_response = null, 
                    status = null, )
            )
        else:
            return TextcustomNamedEntityRecognitionResponseModel(
        )
        """

    def testTextcustomNamedEntityRecognitionResponseModel(self):
        """Test TextcustomNamedEntityRecognitionResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
