# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pydantic_main_textsearch_search_data_class94559368053600 import PydanticMainTextsearchSearchDataClass94559368053600

class TestPydanticMainTextsearchSearchDataClass94559368053600(unittest.TestCase):
    """PydanticMainTextsearchSearchDataClass94559368053600 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PydanticMainTextsearchSearchDataClass94559368053600:
        """Test PydanticMainTextsearchSearchDataClass94559368053600
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PydanticMainTextsearchSearchDataClass94559368053600`
        """
        model = PydanticMainTextsearchSearchDataClass94559368053600()
        if include_optional:
            return PydanticMainTextsearchSearchDataClass94559368053600(
                items = [
                    openapi_client.models.infos_search_data_class.InfosSearchDataClass(
                        object = '', 
                        document = 56, 
                        score = 56, )
                    ],
                original_response = None,
                status = 'success'
            )
        else:
            return PydanticMainTextsearchSearchDataClass94559368053600(
                status = 'success',
        )
        """

    def testPydanticMainTextsearchSearchDataClass94559368053600(self):
        """Test PydanticMainTextsearchSearchDataClass94559368053600"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
