# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.face_facial_hair import FaceFacialHair

class TestFaceFacialHair(unittest.TestCase):
    """FaceFacialHair unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FaceFacialHair:
        """Test FaceFacialHair
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FaceFacialHair`
        """
        model = FaceFacialHair()
        if include_optional:
            return FaceFacialHair(
                moustache = 56,
                beard = 56,
                sideburns = 56
            )
        else:
            return FaceFacialHair(
                moustache = 56,
                beard = 56,
                sideburns = 56,
        )
        """

    def testFaceFacialHair(self):
        """Test FaceFacialHair"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
