# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.imageanonymizationimagelandmark_detectionimageexplicit_content_image_request import ImageanonymizationimagelandmarkDetectionimageexplicitContentImageRequest

class TestImageanonymizationimagelandmarkDetectionimageexplicitContentImageRequest(unittest.TestCase):
    """ImageanonymizationimagelandmarkDetectionimageexplicitContentImageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageanonymizationimagelandmarkDetectionimageexplicitContentImageRequest:
        """Test ImageanonymizationimagelandmarkDetectionimageexplicitContentImageRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageanonymizationimagelandmarkDetectionimageexplicitContentImageRequest`
        """
        model = ImageanonymizationimagelandmarkDetectionimageexplicitContentImageRequest()
        if include_optional:
            return ImageanonymizationimagelandmarkDetectionimageexplicitContentImageRequest(
                providers = '0',
                fallback_providers = '',
                response_as_dict = True,
                attributes_as_list = True,
                show_original_response = True,
                file = bytes(b'blah'),
                file_url = ''
            )
        else:
            return ImageanonymizationimagelandmarkDetectionimageexplicitContentImageRequest(
                providers = '0',
        )
        """

    def testImageanonymizationimagelandmarkDetectionimageexplicitContentImageRequest(self):
        """Test ImageanonymizationimagelandmarkDetectionimageexplicitContentImageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
