# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.imageembeddings_embeddings_data_class import ImageembeddingsEmbeddingsDataClass

class TestImageembeddingsEmbeddingsDataClass(unittest.TestCase):
    """ImageembeddingsEmbeddingsDataClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageembeddingsEmbeddingsDataClass:
        """Test ImageembeddingsEmbeddingsDataClass
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageembeddingsEmbeddingsDataClass`
        """
        model = ImageembeddingsEmbeddingsDataClass()
        if include_optional:
            return ImageembeddingsEmbeddingsDataClass(
                items = [
                    openapi_client.models.embedding_data_class.EmbeddingDataClass(
                        embedding = [
                            56
                            ], )
                    ],
                original_response = None,
                status = 'success'
            )
        else:
            return ImageembeddingsEmbeddingsDataClass(
                status = 'success',
        )
        """

    def testImageembeddingsEmbeddingsDataClass(self):
        """Test ImageembeddingsEmbeddingsDataClass"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
