# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.async_video_analysis_request import AsyncVideoAnalysisRequest

class TestAsyncVideoAnalysisRequest(unittest.TestCase):
    """AsyncVideoAnalysisRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AsyncVideoAnalysisRequest:
        """Test AsyncVideoAnalysisRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AsyncVideoAnalysisRequest`
        """
        model = AsyncVideoAnalysisRequest()
        if include_optional:
            return AsyncVideoAnalysisRequest(
                providers = '0',
                fallback_providers = '',
                show_original_response = True,
                webhook_receiver = '0',
                users_webhook_parameters = {
                    'key' : null
                    },
                file = bytes(b'blah'),
                file_url = ''
            )
        else:
            return AsyncVideoAnalysisRequest(
                providers = '0',
        )
        """

    def testAsyncVideoAnalysisRequest(self):
        """Test AsyncVideoAnalysisRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
