# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.textchat_chat_stream_request import TextchatChatStreamRequest

class TestTextchatChatStreamRequest(unittest.TestCase):
    """TextchatChatStreamRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TextchatChatStreamRequest:
        """Test TextchatChatStreamRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TextchatChatStreamRequest`
        """
        model = TextchatChatStreamRequest()
        if include_optional:
            return TextchatChatStreamRequest(
                providers = '0',
                fallback_providers = '',
                response_as_dict = True,
                attributes_as_list = True,
                show_original_response = True,
                settings = '',
                text = '',
                chatbot_global_action = '',
                previous_history = [
                    {
                        'key' : null
                        }
                    ],
                temperature = 0,
                max_tokens = 1,
                fallback_type = 'rerun'
            )
        else:
            return TextchatChatStreamRequest(
                providers = '0',
        )
        """

    def testTextchatChatStreamRequest(self):
        """Test TextchatChatStreamRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
