# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.data_type_enum import DataTypeEnum

class TestDataTypeEnum(unittest.TestCase):
    """DataTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataTypeEnum(self):
        """Test DataTypeEnum"""
        # inst = DataTypeEnum()

if __name__ == '__main__':
    unittest.main()
