# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.imageobject_detection_response_model import ImageobjectDetectionResponseModel

class TestImageobjectDetectionResponseModel(unittest.TestCase):
    """ImageobjectDetectionResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageobjectDetectionResponseModel:
        """Test ImageobjectDetectionResponseModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageobjectDetectionResponseModel`
        """
        model = ImageobjectDetectionResponseModel()
        if include_optional:
            return ImageobjectDetectionResponseModel(
                microsoft = openapi_client.models.imageobject_detection_object_detection_data_class.imageobject_detectionObjectDetectionDataClass(
                    items = [
                        openapi_client.models.object_item.ObjectItem(
                            label = '', 
                            confidence = 56, 
                            x_min = 56, 
                            x_max = 56, 
                            y_min = 56, 
                            y_max = 56, )
                        ], 
                    original_response = null, 
                    status = null, ),
                google = openapi_client.models.imageobject_detection_object_detection_data_class.imageobject_detectionObjectDetectionDataClass(
                    items = [
                        openapi_client.models.object_item.ObjectItem(
                            label = '', 
                            confidence = 56, 
                            x_min = 56, 
                            x_max = 56, 
                            y_min = 56, 
                            y_max = 56, )
                        ], 
                    original_response = null, 
                    status = null, ),
                amazon = openapi_client.models.imageobject_detection_object_detection_data_class.imageobject_detectionObjectDetectionDataClass(
                    items = [
                        openapi_client.models.object_item.ObjectItem(
                            label = '', 
                            confidence = 56, 
                            x_min = 56, 
                            x_max = 56, 
                            y_min = 56, 
                            y_max = 56, )
                        ], 
                    original_response = null, 
                    status = null, ),
                clarifai = openapi_client.models.imageobject_detection_object_detection_data_class.imageobject_detectionObjectDetectionDataClass(
                    items = [
                        openapi_client.models.object_item.ObjectItem(
                            label = '', 
                            confidence = 56, 
                            x_min = 56, 
                            x_max = 56, 
                            y_min = 56, 
                            y_max = 56, )
                        ], 
                    original_response = null, 
                    status = null, ),
                api4ai = openapi_client.models.imageobject_detection_object_detection_data_class.imageobject_detectionObjectDetectionDataClass(
                    items = [
                        openapi_client.models.object_item.ObjectItem(
                            label = '', 
                            confidence = 56, 
                            x_min = 56, 
                            x_max = 56, 
                            y_min = 56, 
                            y_max = 56, )
                        ], 
                    original_response = null, 
                    status = null, ),
                sentisight = openapi_client.models.imageobject_detection_object_detection_data_class.imageobject_detectionObjectDetectionDataClass(
                    items = [
                        openapi_client.models.object_item.ObjectItem(
                            label = '', 
                            confidence = 56, 
                            x_min = 56, 
                            x_max = 56, 
                            y_min = 56, 
                            y_max = 56, )
                        ], 
                    original_response = null, 
                    status = null, ),
                eden_ai = openapi_client.models.imageobject_detection_object_detection_data_class.imageobject_detectionObjectDetectionDataClass(
                    items = [
                        openapi_client.models.object_item.ObjectItem(
                            label = '', 
                            confidence = 56, 
                            x_min = 56, 
                            x_max = 56, 
                            y_min = 56, 
                            y_max = 56, )
                        ], 
                    original_response = null, 
                    status = null, )
            )
        else:
            return ImageobjectDetectionResponseModel(
        )
        """

    def testImageobjectDetectionResponseModel(self):
        """Test ImageobjectDetectionResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
