# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.invoice_parser_api import InvoiceParserApi


class TestInvoiceParserApi(unittest.TestCase):
    """InvoiceParserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvoiceParserApi()

    def tearDown(self) -> None:
        pass

    def test_ocr_ocr_invoice_parser_create(self) -> None:
        """Test case for ocr_ocr_invoice_parser_create

        Invoice Parser
        """
        pass


if __name__ == '__main__':
    unittest.main()
