# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sentiment_b6e_enum import SentimentB6eEnum

class TestSentimentB6eEnum(unittest.TestCase):
    """SentimentB6eEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSentimentB6eEnum(self):
        """Test SentimentB6eEnum"""
        # inst = SentimentB6eEnum()

if __name__ == '__main__':
    unittest.main()
