# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.automl_classification_api import AutomlClassificationApi


class TestAutomlClassificationApi(unittest.TestCase):
    """AutomlClassificationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AutomlClassificationApi()

    def tearDown(self) -> None:
        pass

    def test_image_image_automl_classification_create_project_create(self) -> None:
        """Test case for image_image_automl_classification_create_project_create

        Automl Classification - Create Project
        """
        pass

    def test_image_image_automl_classification_delete_project_create(self) -> None:
        """Test case for image_image_automl_classification_delete_project_create

        Automl Classification - Delete Project
        """
        pass

    def test_image_image_automl_classification_list_projects_retrieve(self) -> None:
        """Test case for image_image_automl_classification_list_projects_retrieve

        Automl Classification - List Projects
        """
        pass

    def test_image_image_automl_classification_predict_async_create(self) -> None:
        """Test case for image_image_automl_classification_predict_async_create

        Automl Classification Predict Launch Job
        """
        pass

    def test_image_image_automl_classification_predict_async_retrieve(self) -> None:
        """Test case for image_image_automl_classification_predict_async_retrieve

        Automl Classification Predict List Job
        """
        pass

    def test_image_image_automl_classification_predict_async_retrieve2(self) -> None:
        """Test case for image_image_automl_classification_predict_async_retrieve2

        Automl Classification - Predict Get Job Results
        """
        pass

    def test_image_image_automl_classification_train_async_create(self) -> None:
        """Test case for image_image_automl_classification_train_async_create

        Automl Classification Train Launch Job
        """
        pass

    def test_image_image_automl_classification_train_async_retrieve(self) -> None:
        """Test case for image_image_automl_classification_train_async_retrieve

        Automl Classification Train List Job
        """
        pass

    def test_image_image_automl_classification_train_async_retrieve2(self) -> None:
        """Test case for image_image_automl_classification_train_async_retrieve2

        Automl Classification - Train Get Job Results
        """
        pass

    def test_image_image_automl_classification_upload_data_async_create(self) -> None:
        """Test case for image_image_automl_classification_upload_data_async_create

        Automl Classification Upload Data Launch Job
        """
        pass

    def test_image_image_automl_classification_upload_data_async_retrieve(self) -> None:
        """Test case for image_image_automl_classification_upload_data_async_retrieve

        Automl Classification Upload Data List Job
        """
        pass

    def test_image_image_automl_classification_upload_data_async_retrieve2(self) -> None:
        """Test case for image_image_automl_classification_upload_data_async_retrieve2

        Automl Classification - Upload Data Get Job Results
        """
        pass


if __name__ == '__main__':
    unittest.main()
