# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.add_url_request import AddUrlRequest

class TestAddUrlRequest(unittest.TestCase):
    """AddUrlRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddUrlRequest:
        """Test AddUrlRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddUrlRequest`
        """
        model = AddUrlRequest()
        if include_optional:
            return AddUrlRequest(
                urls = [
                    '0'
                    ],
                metadata = [
                    {
                        'key' : null
                        }
                    ]
            )
        else:
            return AddUrlRequest(
                urls = [
                    '0'
                    ],
        )
        """

    def testAddUrlRequest(self):
        """Test AddUrlRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
