# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.face_detection_async_api import FaceDetectionAsyncApi


class TestFaceDetectionAsyncApi(unittest.TestCase):
    """FaceDetectionAsyncApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FaceDetectionAsyncApi()

    def tearDown(self) -> None:
        pass

    def test_video_video_face_detection_async_create(self) -> None:
        """Test case for video_video_face_detection_async_create

        Face Detection Launch Job
        """
        pass

    def test_video_video_face_detection_async_destroy(self) -> None:
        """Test case for video_video_face_detection_async_destroy

        Face Detection delete Jobs
        """
        pass

    def test_video_video_face_detection_async_retrieve(self) -> None:
        """Test case for video_video_face_detection_async_retrieve

        Face Detection List Jobs
        """
        pass

    def test_video_video_face_detection_async_retrieve2(self) -> None:
        """Test case for video_video_face_detection_async_retrieve2

        Face Detection Get Job Results
        """
        pass


if __name__ == '__main__':
    unittest.main()
