# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.identification_numbers_sub_category_type import IdentificationNumbersSubCategoryType

class TestIdentificationNumbersSubCategoryType(unittest.TestCase):
    """IdentificationNumbersSubCategoryType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentificationNumbersSubCategoryType(self):
        """Test IdentificationNumbersSubCategoryType"""
        # inst = IdentificationNumbersSubCategoryType()

if __name__ == '__main__':
    unittest.main()
