# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.textprompt_optimization_response_model import TextpromptOptimizationResponseModel

class TestTextpromptOptimizationResponseModel(unittest.TestCase):
    """TextpromptOptimizationResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TextpromptOptimizationResponseModel:
        """Test TextpromptOptimizationResponseModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TextpromptOptimizationResponseModel`
        """
        model = TextpromptOptimizationResponseModel()
        if include_optional:
            return TextpromptOptimizationResponseModel(
                openai = openapi_client.models.textprompt_optimization_prompt_optimization_data_class.textprompt_optimizationPromptOptimizationDataClass(
                    missing_information = '', 
                    items = [
                        openapi_client.models.prompt_data_class.PromptDataClass(
                            text = '', )
                        ], 
                    original_response = null, 
                    status = null, )
            )
        else:
            return TextpromptOptimizationResponseModel(
        )
        """

    def testTextpromptOptimizationResponseModel(self):
        """Test TextpromptOptimizationResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
