# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.document_translation_api import DocumentTranslationApi


class TestDocumentTranslationApi(unittest.TestCase):
    """DocumentTranslationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentTranslationApi()

    def tearDown(self) -> None:
        pass

    def test_translation_translation_document_translation_create(self) -> None:
        """Test case for translation_translation_document_translation_create

        Document Translation
        """
        pass


if __name__ == '__main__':
    unittest.main()
