# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.type_of_data_enum import TypeOfDataEnum

class TestTypeOfDataEnum(unittest.TestCase):
    """TypeOfDataEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypeOfDataEnum(self):
        """Test TypeOfDataEnum"""
        # inst = TypeOfDataEnum()

if __name__ == '__main__':
    unittest.main()
