# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.question_answer_api import QuestionAnswerApi


class TestQuestionAnswerApi(unittest.TestCase):
    """QuestionAnswerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QuestionAnswerApi()

    def tearDown(self) -> None:
        pass

    def test_image_image_question_answer_create(self) -> None:
        """Test case for image_image_question_answer_create

        Question Answer
        """
        pass

    def test_text_text_question_answer_create(self) -> None:
        """Test case for text_text_question_answer_create

        Question Answer
        """
        pass


if __name__ == '__main__':
    unittest.main()
