# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.universal_translator_call_request import UniversalTranslatorCallRequest

class TestUniversalTranslatorCallRequest(unittest.TestCase):
    """UniversalTranslatorCallRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UniversalTranslatorCallRequest:
        """Test UniversalTranslatorCallRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UniversalTranslatorCallRequest`
        """
        model = UniversalTranslatorCallRequest()
        if include_optional:
            return UniversalTranslatorCallRequest(
                text = '0',
                source_language = '',
                target_language = '0'
            )
        else:
            return UniversalTranslatorCallRequest(
                text = '0',
                target_language = '0',
        )
        """

    def testUniversalTranslatorCallRequest(self):
        """Test UniversalTranslatorCallRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
