# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.anonymization_api import AnonymizationApi


class TestAnonymizationApi(unittest.TestCase):
    """AnonymizationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnonymizationApi()

    def tearDown(self) -> None:
        pass

    def test_image_image_anonymization_create(self) -> None:
        """Test case for image_image_anonymization_create

        Anonymization
        """
        pass

    def test_text_text_anonymization_create(self) -> None:
        """Test case for text_text_anonymization_create

        Anonymization
        """
        pass


if __name__ == '__main__':
    unittest.main()
