# coding: utf-8

"""
    Eden AI

    Your project description

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.hate_and_extremism_sub_category_type import HateAndExtremismSubCategoryType

class TestHateAndExtremismSubCategoryType(unittest.TestCase):
    """HateAndExtremismSubCategoryType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHateAndExtremismSubCategoryType(self):
        """Test HateAndExtremismSubCategoryType"""
        # inst = HateAndExtremismSubCategoryType()

if __name__ == '__main__':
    unittest.main()
